import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import favicon from "@/app/favicon.ico"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./favicon.ico" sizes="any" />
      </head>
      <body
        className=' w-full antialiased flex  select-none overflow-x-hidden gap-[-10px]'
      >
        <div className=" flex-[26%] border-r-1 border-r-[#2F3336]  overflow-hidden ">
          <Sidebar />
        </div>
        <div className="flex-[74%]   ">
          {children}
        </div>
      </body>
    </html>
  );
}
